# Fast development version - minimal services
version: '3.8'

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  DATABASE_PASSWORD: vapor_password
  AUTO_MIGRATE: "true"

services:
  app:
    image: safeandbrave:latest
    build:
      context: .
      target: build  # Stop at build stage for faster iteration
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_started  # Don't wait for health check
    ports:
      - '8080:8080'
    networks:
      - safeandbrave
    volumes:
      # Mount source code for hot reloading (if supported)
      - ./Sources:/build/Sources:ro
      - ./Resources:/build/Resources:ro
    command: ["serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]
  
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
      POSTGRES_INITDB_ARGS: "--data-checksums=off"
    ports:
      - '5432:5432'
    networks:
      - safeandbrave
    command: >
      postgres
      -c shared_buffers=128MB
      -c effective_cache_size=512MB
      -c maintenance_work_mem=32MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=8MB
      -c default_statistics_target=50
      -c random_page_cost=1.1
      -c work_mem=2MB
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
    # Remove health check for faster startup
    # healthcheck: disabled

networks:
  safeandbrave: